add documentation on EESSI test suite (WIP)
EESSI/docs pull request #110
Opened 2023-09-07 09:09 UTC by boegel

Work-in-progress, this page is still being actively developed via https://hackmd.io/TUjhmb32SnertH9nD2Flaw

It is meant to eventually replace http://www.eessi.io/docs/software_testing, which is very outdated right now

2023-09-21 16:21 UTC, smoors commented on docs/test-suite/usage.md
> +    When using `--list`, checks are only generated based on available modules.
```suggestion
    When using `--list`, checks are only generated based on modules that are available in the system where the `reframe` command is invoked.
```

2023-09-21 16:21 UTC, smoors commented on docs/test-suite/usage.md
> +### Dry run of TensorFlow CI checks on a quarter node (on all system partitions)
```suggestion
### Dry run of TensorFlow CI checks on a quarter (1/4) of a node (on all system partitions)
```

2023-09-21 16:21 UTC, smoors commented
should we also say something about multi-threading?

2023-09-21 16:27 UTC, smoors commented on docs/test-suite/usage.md
> +| `4_cores` | using 4 CPU cores, or 4 GPUs |
this is not entirely correct
```suggestion
| `1_core` | using 1 CPU core and 1 GPU (if running a GPU test) |
| `2_cores` | using 2 CPU cores and 1 GPU (if running a GPU test) |
| `4_cores` | using 4 CPU cores, or 4 GPUs and 1 GPU (if running a GPU test) |
```

2023-10-02 07:03 UTC, boegel commented
@smoors All suggestions applied, good to go now?

2023-10-02 07:32 UTC, smoors commented on docs/test-suite/usage.md
> +| `4_cores` | using 4 CPU cores, or 4 GPUs and 1 GPU (if running a GPU test) |
```suggestion
| `4_cores` | using 4 CPU cores and 1 GPU (if running a GPU test) |
```

2023-10-02 07:36 UTC, smoors commented
> @smoors All suggestions applied, good to go now?

almost, just one fix (see above)

2023-10-02 07:57 UTC, smoors approved these changes
lgtm

2023-10-02 07:58 UTC, smoors commented
all good for me, but i don't have merge rights

2023-10-04 13:04 UTC, casparvl requested changes

2023-10-04 13:44 UTC, casparvl approved these changes
Lgtm!

2023-10-04 13:44 UTC, merged