Update landing page
EESSI/docs pull request #120
Opened 2023-10-25 13:09 UTC by xinan1911

Update index.md to make landing page for eessi.io/docs more useful

2023-10-30 09:32 UTC, casparvl commented on docs/index.md
> +* [Access](getting_access/is_eessi_accessible.md), [configure](setting_up_environment.md) and [use](basic_commands.md) EESSI
should be `using_eessi/setting_up_environment.md` (same for the other WARNINGs in the CI)

2023-11-07 08:23 UTC, ocaisa requested changes

2023-11-07 08:23 UTC, ocaisa commented on docs/index.md
> -
Why drop this?

2023-11-07 08:23 UTC, ocaisa commented on docs/index.md
> +
We're missing the last three items from the original list here, are these deliberate omissions? I think we at least want to keep the contact link around

2023-11-13 13:11 UTC, closed without merging