add blog to EESSI docs + post on ISC'24
EESSI/docs pull request #178
Opened 2024-05-18 08:42 UTC by boegel

preview available at https://boegel.github.io/EESSI-docs/blog/2024/05/17/isc24

Don't merge this yet, since images a broken at https://boegel.github.io/EESSI-docs/blog, need to figure out if we can fix that (ideally without hardcoding image URLs...)

Feedback on text is already welcome though!

2024-05-18 10:21 UTC, jpecar commented
I also made tensortorrent people at their booth aware of eessi risc-v efforts, if that counts ...

2024-05-18 11:13 UTC, boegel commented
> I also made tensortorrent people at their booth aware of eessi risc-v efforts, if that counts ...

Lots of additional informal contacts were made beyond what the blog post covers were made by as well, I was mostly going for things that are tangible: part of ISC'24 official program or exhibit, talks by invitation, etc.

If the contacts with TensorTorrent materialize into something worth reporting over, we can write up a dedicated blog post on just that?

2024-05-18 12:21 UTC, trz42 submitted a review, later dismissed
Nice and concise.

2024-05-18 12:21 UTC, trz42 commented on docs/blog/posts/2024/05/isc24.md
> +are actively involved in, and through which the development of EESSI is being funded since Jan'23,
Maybe

```suggestion
are actively involved in, and through which the development of EESSI is being co-funded since Jan'23,
```

2024-05-18 12:21 UTC, trz42 commented on docs/blog/posts/2024/05/isc24.md
> +During the last day of ISC'24, EESSI was present is no less than *three* different
Small typo
```suggestion
During the last day of ISC'24, EESSI was present in no less than *three* different
```

2024-05-21 08:52 UTC, casparvl commented on docs/blog/posts/2024/05/isc24.md
> +through an **interactive poll** and letting attendees ask questions.
```suggestion
through an **interactive poll** and by letting attendees ask questions.
```

2024-05-21 11:57 UTC, boegel commented on docs/blog/posts/2024/05/isc24.md
> +through an **interactive poll** and letting attendees ask questions.
@ocaisa ?

2024-05-21 13:11 UTC, ocaisa requested changes
Text reads well. The pictures are unnecessarily large and will make the page slow to load. 

Webp is a better format for file size, and a 720p size should be more than enough

2024-05-21 13:39 UTC, boegel commented
@ocaisa pictures resized to 720p, whole subdirectory went from 14MB to ~700kB

2024-05-21 14:10 UTC, boegel commented
> If we get serious about a blog, we should add CI to check image sizes, repo will get slow if we start add a lot of big binary files

Agreed, but let's tackle that in a follow-up PR?

2024-05-21 14:12 UTC, merged